### ISSUE TITLE
Server crash on 1.21

### ISSUE THREAD

**Issue by sternschnaube** [fooeyround/Configured#2]
### Bug description

https://pastebin.com/raw/1Mj86ZY2

### Steps to reproduce

/

### Minecraft version

1.21

### TemplateMod version

1.3.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by fooeyround** [comment]
Yes, thank you for reporting this. It seems I did not adequately check the mixins and the validity of their signatures.

I hope to fix this soon, do you disable end gateways with the mod? I could disable the crash with just that feature not present, as I lack the development environment needed to inspect the updated vanilla Minecraft code...
It seems that (hopefully) previous versions still work. 

I will fix this as soon as possible.

**Comment by venaminecraft** [comment]
Thank you! 😊 

I was not disabling end gateways with this mod, the crash doesn't allow me to use any feature yet.
I should have included Carpet extensions with rules for the End dimension.

**Comment by fooeyround** [comment]
Hopefully my recent commits will stop the game from crashing. The broken feature will still not work, but I will fix that when I can. 

I hope you continue to enjoy using the mod, if you have any feature requests, don't be afraid to open an issue with the feature request template.

(I will be making a release soon)

(A link to the build. It will be released soon though, so you will be able to find it on modrinth or in GitHub releases)
https://github.com/fooeyround/Configured/actions/runs/9625711776/artifacts/1627582450

**Comment by venaminecraft** [comment]
Tested, mod works now. Thank you 😄
